#!/usr/bin/env python

# takes a single parameter YYYYMM
# creates a new file, rta.<YYYYMM>.dex that is the same as rta.<YYYYMM> but is limited to ONLY HETDEX science observations
# this can then be used to conduct the VDRP astrometry step


import os
import sys
import numpy as np


cl_args = list(map(str.lower,sys.argv))

path = "./"

yyyymm = int(cl_args[1])

hdrXfn = "/scratch/03261/polonius/science_reductions/hdrX.use"
rtafn = f"rta.{yyyymm}"
outfn = f"rta.{yyyymm}.dex" #hetdex only

dates,shots = np.loadtxt(hdrXfn,unpack="True",dtype=int)
sel = [str(d)[0:6]==str(yyyymm) for d in dates]
dates = dates[sel]
shots = shots[sel]
all_dvs = [f"{d}v{str(s).zfill(3)}" for d,s in zip(dates,shots)]

with open(os.path.join(path,rtafn),"r") as f1:
    with open(os.path.join(path,outfn),"w") as f2:
        for line in f1:
            #print(line)
            toks = line.split()
            dvs = f"{toks[1]}v{toks[2]}"
            if dvs in all_dvs:
                f2.write(line)
