#!/usr/bin/env python

#takes 3 parameters
#1) hdf5 file to open that has the Detections table 
#2) output file to list matching detectids
#3) selection string to use for the simple query: e.g  "date >= 20240400"  or "(date > 20240300) & (date < 20240400)"

import tables 
import numpy as np
import sys

cl_args = list(map(str,sys.argv)) 
h5fn = cl_args[1]
outfn = cl_args[2]
selection = cl_args[3]

h5 = tables.open_file(h5fn)

detectids = h5.root.Detections.read_where(selection,field="detectid")

h5.close()
print(f"Found {len(detectids)}")

#print(detectids)

if len(detectids) > 0:
    np.savetxt(outfn,np.unique(detectids),fmt="%d")

