#!/usr/bin/env python

#
# check the output of rcal_all
#
# takes a single input, YYYYMM


import glob
import os
import sys
import numpy as np
from tqdm import tqdm


#workpath = "/scratch/03261/polonius/science_reductions/alldet/"
#outpath = "/scratch/03261/polonius/science_reductions/alldet/cal_out/" 
workpath = "./"
outpath = "./cal_out/" 


cl_args = list(map(str.lower,sys.argv)) 
#cl_args = ["","202309"]

try:
    yyyymm = int(cl_args[1])
    ref_fn = f"rcal_all_{yyyymm}.run"
except:
    yyyymm = None
    ref_fn = cl_args[1]

#open the run file
#fmt 
# rcal_all 27.1180630 -1.6516663 35 4505 50 514_103_019 20230925v021 1.70 3.0 3.5 0.5 3 106


ifus, datevshots = np.loadtxt(os.path.join(workpath,ref_fn),usecols=[6,7],dtype=str,unpack=True)


missing_shots = []
missing_files = []

for i,d in tqdm(zip(ifus,datevshots),total=len(datevshots)):
    #check that the file exists
    fitsname=d+"_"+i+"_cal.fits"
    if not os.path.exists(os.path.join(outpath,fitsname)):
        missing_files.append(os.path.join(outpath,fitsname))
        if d not in missing_shots:
            missing_shots.append(d)
        #else:
            #check the size?


if len(missing_shots) == 0:
    print("Done. All shots found.")
else:
    print(f"Done. {len(missing_files)} files missing for {len(missing_shots)} shots missing.")
    print("Files:")
    for f in missing_files:
        print(f)
    print("\n\nShots:")
    for f in missing_shots:
        print(f)
