#!/usr/bin/env python

#import numpy as np
import os
import sys
import glob
from tqdm import tqdm

cl_args = list(map(str.lower,sys.argv))
try:
    match = cl_args[1]
except:
    match = "*"

files = sorted(glob.glob(f"./output/d{match}amp.dat"))

with open("rgetamp0","w") as f:
    for file in tqdm(files):
        b = os.path.basename(file)
        f.write(f"rgetamp {b[1:9]} {b[10:13]} {b[13:18]}\n")

os.chmod("rgetamp0", 0o775)
