#!/usr/bin/env python

#takes (optionally) 1 parameter YYYYMM 


import glob
import os
import sys
import numpy as np
#from tqdm import tqdm

cl_args = list(map(str.lower,sys.argv))

path = "./tp/"

try:
    yyyymm = int(cl_args[1])
    if len(str(yyyymm)) != 6:
        yyyymm = "??????"
        print("Checking all files.")
except:
    yyyymm = "??????"
    print("Checking all files.")


fns = sorted(glob.glob(f"{path}{yyyymm}??v*sedtp_f.dat"))

print(f"Checking {len(fns)} files under {path} ...")
print( "-----------------------------")
for fn in fns:
    try:
        out = np.loadtxt(fn)
        if np.any(out[:,5]): #5 is the actual throughput, I think and 4 is tied to it? cols 2, 3 don't seem to matter
            continue #all good
        else:
            print(f"bad {os.path.basename(fn)}")
        
    except Exception as E:
        print(E)
print( "-----------------------------")
print("Done.")
