#!/usr/bin/python


import numpy as np
import glob
import os
from astropy.io import fits
from elixer import utilities as utilities
from tqdm import tqdm
import matplotlib
import matplotlib.pyplot as plt
matplotlib.use('agg')

basedir = "./"

amps = ['RU','RL','LL','LU']
#useful   no     no    yes    no    ??      ??    yes?
exts = ['cbwt','cbxt','cmbf','cmsf','cmsp','cswt','csxt']
#       (9,6)  (9,6)  (9,6)  (9,6)   ?,?   (9,6)  (9,6)
all_fns = glob.glob(f"{basedir}/i???a*.fits")
all_ifus = sorted(np.unique([os.path.basename(x)[1:4] for x in all_fns]))


cmap = "gray"
for ifu in tqdm(all_ifus):
    for ext in exts:
        #this is the working bit ... combine all amps into a single image for the give ifu + ext
        plt.close('all')
        if ext == 'cmsp':
            fig, axes = plt.subplots(nrows=1, ncols=4, figsize=(12,4))
        else:
            fig, axes = plt.subplots(nrows=4, ncols=1, figsize=(9,6))
        for ai, amp in enumerate(amps):
            ax = axes[ai]
            fn = os.path.join(basedir,f"i{ifu}a{amp}{ext}.fits")
            try:
                hdu = fits.open(fn)

                ax.set_title(f"{ifu} {amp} {ext}")
                vmin,vmax=utilities.get_vrange(hdu[0].data,contrast=0.25)
                ax.imshow(hdu[0].data,cmap=cmap,vmin=vmin,vmax=vmax)
                plt.tight_layout()

                hdu.close()
            except:
                pass
        plt.tight_layout()
        plt.savefig(f"i{ifu}_{ext}.png",dpi=96)


