#!/usr/bin/env python


# takes one required parameter, YYYYMM
# copies the dithall.use under each directory to dithall, stripping off the header line, and renaming to the <shot>.dithall

import glob
import os
import sys
from tqdm import tqdm

cl_args = list(map(str.lower,sys.argv))

path = "./" #"/scratch/03261/polonius/science_reductions/vdrp/shifts/"

yyyymm = int(cl_args[1])

dirs = glob.glob(f"{path}{yyyymm}??v*")

for d in tqdm(dirs):
    try:
        with open(os.path.join(d,"dithall.use"),"r") as f1:
        #skip 1st line
            _ = f1.readline()
            outfn = os.path.basename(d)
            outfn = os.path.join(path,f"dithall/{outfn}.dithall")
            with open(outfn,"w+") as f2:
                for line in f1:
                    f2.write(line)
    except Exception as E:
        print(E)

