#!/usr/bin/env python

#if no parameter, just print the total number of shots left to run (e.g. that are not either already complete
#  or are in progress / in queue)
#if "-v"  the print each shot that needs to be done to stdout

import numpy as np
import os
import sys
from tqdm import tqdm

cl_args = list(map(str.lower,sys.argv))

try:

	if len(cl_args) == 1:
		#do nothing
		verbose = False
	elif len(cl_args) == 2:
		if cl_args[1] == "-v":
			verbose = True
		else:
			print(f"{cl_args[1]} bad switch")
			exit(0)
	else:
		print(f"{cl_args} bad command")
		exit(-1)
except:
	verbose = False

all_shots = np.loadtxt("all_official.shots",unpack=True,dtype=str)

todo_count = 0
todo_shots = []

for shot in tqdm(all_shots):
	dirname = f"sim{shot[0:8]}v{shot[8:]}s666"
	simname = f"{shot[0:8]}v{shot[8:]}s666.sim"
	#skip if I have it already or Karl has it already
	#note: Owen has been running on lonestar6 and we can't readily see that /scratch from here
	if  os.path.exists(dirname) or os.path.exists(os.path.join("done",dirname)) or \
		os.path.exists(os.path.join("/scratch/00115/gebhardt/sim",dirname)) or \
                os.path.isfile(os.path.join("/corral-repl/utexas/Hobby-Eberly-Telesco/sims/orig",simname)) or \
		os.path.isfile(os.path.join("/corral-repl/utexas/Hobby-Eberly-Telesco/sims_dd/orig", simname)) or \
		os.path.isfile(os.path.join("/work/06890/ochase10/ls6/random_sims/sims", simname)):
	#	print(f"{shot} already done or in-progress. Skipping.")
		continue

	todo_count += 1
	todo_shots.append(shot)


if verbose:
	for s in todo_shots:
		print(s)
else:
	print(f"{todo_count} shots remaining (not complete or in progress)")
