#!/usr/bin/env python

# takes two arguments: (1) which queue ... string: [skx, spr]
#                      (2) how many (N) jobs or shots to queue
# then reads todo.txt and builds/queues the first N that do not already have a directory created or is already done or /corral/
# ASSUMES the rmksim0c/d ends with the call to rstep1 (otherwise, if that is commented out, the directory is created, but the job is not queued)
#
# NOTICE: each directory can take a few minutes to create due to the fetching and untarring
#

import numpy as np
import os
import sys

cl_args = list(map(str.lower,sys.argv))

queue = cl_args[1]
count = int(cl_args[2])
rgetran = None

if queue == "skx":
	rgetran = "./rgetran"
elif queue == "spr":
	rgetran = "./rgetran_spr"
else:
	print("invalid queue")
	exit(-1)
	

shots_todo = np.loadtxt("todo.txt",unpack=True,dtype=str)

for shot in shots_todo:
	
	dirname = f"sim{shot[0:8]}v{shot[8:]}s666"
	simname = f"{shot[0:8]}v{shot[8:]}s666.sim"
	#skip if I have it already or Karl has it already
	#note: Owen has been running on lonestar6 and we can't readily see that /scratch from here
	if os.path.exists(dirname) or os.path.exists(os.path.join("/scratch/00115/gebhardt/sim",dirname)) or \
           os.path.isfile(os.path.join("/corral-repl/utexas/Hobby-Eberly-Telesco/sims/orig",simname)) or \
           os.path.isfile(os.path.join("/work/06890/ochase10/ls6/random_sims/sims", simname)):
		print(f"{shot} already done or in-progress. Skipping.")
		continue

	print(f"\n{shot} not found. Creating ... ")
	print(f"{count} remaining ...")
	
		
	cmd = f"$({rgetran} {shot[0:8]} {shot[8:]})"
	#cmd = f"echo testing dummy  command {shot[0:8]} {shot[8:]}"
	os.system(cmd)
	count -= 1
	
	if count == 0:
		break
		

