#!/usr/bin/env python

# TEMPORARY?? rebuild existing (old) cosmology sims slurm files with the new, recoverable entries

#import numpy as np
import os
import sys
import glob
#import shutil

basedir = os.getcwd() #or spcify
original_basedir = os.getcwd()
#basedir = ""
os.chdir(basedir)

cl_args = list(map(str.lower,sys.argv))
slurm_fn = cl_args[1]
dir_j = slurm_fn.split(".")[0]

#!!! again, limited error control ... I want this to abend on an exception

queue = None
per_job_shot_count = 0
all_subdir = []

with open(slurm_fn,"r") as f:
	lines = f.readlines() ## all the lines

	#find the queue
	for line in lines:
		if "#SBATCH -p " in line:
			#found it ... even if more than one, assume first one is true
			toks = line.split()
			queue = toks[toks.index(("-p"))+1]
			break

	if queue is None:
		print("Fatal. Could not identify queue.")
		exit(-1)


	#find the tasks ntasks #SBATCH --ntasks 48        # using --ntasks for consistency with spr, but same as --ntasks_per_node
	ntasks = None
	for line in lines:
		if "#SBATCH --ntasks " in line:
			#found it ... even if more than one, assume first one is true
			toks = line.split()
			ntasks = toks[toks.index(("--ntasks"))+1]
			break

	if ntasks is None:
		print("Fatal. Could not identify ntasks.")
		exit(-1)

	#how many jobs are there?
	last_job_ct = 0
	for line in lines:
		if "Starting sim #" in line:
			per_job_shot_count += 1
			toks = line.split()
			j = toks[toks.index(("sim"))+1]
			last_job_ct = int(j[1:])

	if per_job_shot_count != last_job_ct:
		print(f"Fatal. Could not match job counts {per_job_shot_count} != {last_job_ct}.")
		exit(-1)

	#what are the directories
	for line in lines:
		if "cd sim20" in line:
			toks = line.split()
			all_subdir.append(toks[1])


	if len(all_subdir) != per_job_shot_count:
		print(f"Fatal. Could not match subdirs to job counts {len(all_subdir)} != {per_job_shot_count}.")
		exit(-1)



#get the total number of IFUEs
total_ifus = 0 #reset ... total ifus in THIS job
for subdir in (all_subdir):
	total_ifus += len(glob.glob(f"{dir_j}/{subdir}/sources/*.001"))



#approximate time needed, with slop for variablility in TACC I/O performance
# time depends on size of copy (which is largely proportional to the number of IFUs) and number of IFUs
hours = 0.2 * per_job_shot_count + total_ifus / 500
minutes = int((hours - int(hours)) * 60)
hours = int(hours)

print(f"{per_job_shot_count} shots")
print(f"{total_ifus} total_ifus")
print(f"{hours}:{minutes}:00")

#copy the original
cmd = f"cp {slurm_fn} {slurm_fn}.original"
os.system(cmd)

with open(f"{slurm_fn}","w") as f:

	f.write("#!/bin/bash \n")
	f.write("#SBATCH -J hetdex                # Job name\n")
	f.write("#SBATCH -N 1                     # Total number of nodes requested\n")
	f.write(f"#SBATCH --ntasks {ntasks}        # using --ntasks for consistency with spr, but same as --ntasks_per_node\n")
	f.write("#SBATCH -p skx                   # Queue name\n")
	f.write(f"#SBATCH -o HETDEX{dir_j}.o%j    # Name of stdout output file (%j expands to jobid)\n")
	f.write(f"#SBATCH -t {hours}:{minutes}:00              # Run time (hh:mm:ss)\n")
	f.write("#SBATCH -A Hobby-Eberly-Telesco\n")
	f.write("#SBATCH --mail-user dustin@astro.as.utexas.edu\n")
	f.write("#SBATCH --mail-type all\n")
	f.write("\n")
	f.write("module load pylauncher/5.2\n")
	f.write("module load cdtools\n")
	f.write("\n")
	f.write(f"cd {dir_j}\n")
	f.write("export LAUNCHER_WORKDIR=$(pwd)\n") #just temporary, actual workdir will be in each shot directory
	f.write("WORKDIR=$LAUNCHER_WORKDIR\n")
	f.write("\n")


	#serialize over the individual sims here
	#change_date, change_shot, change_datevshot
	simnum = 0
	for subdir in all_subdir:

		change_date = subdir[3:11] #just for consistency with old code
		change_shot = subdir[12:15]

		simnum += 1
		change_datevshot = f"{change_date}v{change_shot}"
		f.write("\n")
		f.write("##########################################\n")
		f.write(f"if [ -f {subdir}/{change_date}v{change_shot}.running ]; then\n")
		f.write(f"  echo skipping {change_date}v{change_shot}. Already done or in-progress.\n")

		f.write(f"else\n")
		#ELSE branch ... exectue the shot mock
		f.write(f"  echo \"Starting sim #{simnum} ({change_datevshot})... \"\n")
		f.write(f"  cd {subdir}\n")
		f.write("  export LAUNCHER_WORKDIR=$(pwd)\n")
		f.write("  WORKDIR=$LAUNCHER_WORKDIR\n")
		f.write("\n")

		f.write(f"  touch {change_datevshot}.running \n")  # set a run flag as a file for easy checking

		f.write(f"  distribute.bash	raw/{change_date}/virus/virus0000{change_shot}.tar\n")
		f.write(f"  distribute.bash	datafiles/{change_datevshot}.dithall\n")
		f.write(f"  distribute.bash	datafiles/{change_datevshot}sedtp_f.dat\n")
		f.write("  distribute.bash	datafiles/fluxcor.use\n")
		f.write("  distribute.bash	datafiles/fwhm.use\n")
		f.write("  distribute.bash	datafiles/norm.dat\n")
		f.write("  wait\n")
		f.write("\n")
		f.write("  export LAUNCHER_WORKDIR=$(pwd)\n")
		f.write("  export LAUNCHER_JOB_FILE=rt1c\n")
		f.write("  WORKDIR=$LAUNCHER_WORKDIR\n")
		f.write("  CONTROL_FILE=$LAUNCHER_JOB_FILE\n")
		f.write("  cd $WORKDIR/\n")
		f.write("  echo \" WORKING DIR:   $WORKDIR/\"\n")
		f.write("  run_pylauncher\n")
		f.write("\n")
		f.write("  wait\n")
		f.write(f"  echo \"FIRST PART {change_datevshot}\" \n")
		f.write("\n")
		f.write("  export LAUNCHER_JOB_FILE=rt1\n")
		f.write("  CONTROL_FILE=$LAUNCHER_JOB_FILE\n")
		f.write("  run_pylauncher\n")
		f.write("  wait\n")
		f.write("\n")
		f.write("  runpost\n")
		f.write("  echo \"cleaning /tmp ...\"\n")
		f.write("  rm -rf /tmp/virus*\n")
		f.write("  rm -rf /tmp/20*\n")
		f.write("  rm -rf /tmp/ras20*\n")
		f.write("  rm -rf /tmp/fluxcor.use\n")
		f.write("  rm -rf /tmp/fwhm.use\n")
		f.write("  rm -rf /tmp/norm.dat\n")
		f.write(f"  echo \"Done sim #{simnum} ({change_datevshot})... \"\n")
		f.write(f"  touch {change_datevshot}.done \n") #set a done flag as a file for easy checking
		f.write(f"  cd .. \n")
		f.write(f"fi\n")

