#!/usr/bin/env python


# takes a single paramater, YYYYMM
# removes .dithall files under the dithall directory that do not correspond to HETDEX science shots 
#   note: those files are also probably empty anyway

import glob
import os
import sys
import numpy as np
from tqdm import tqdm

cl_args = list(map(str.lower,sys.argv))

path = "./dithall/"

yyyymm = int(cl_args[1])

hdrXfn = "/scratch/03261/polonius/science_reductions/hdrX.use"
dates,shots = np.loadtxt(hdrXfn,unpack="True",dtype=int)


sel = [str(d)[0:6]==str(yyyymm) for d in dates]

dates = dates[sel]
shots = shots[sel]


all_dvs = [f"{d}v{str(s).zfill(3)}" for d,s in zip(dates,shots)]

fns = glob.glob(f"{path}{yyyymm}*")

if len(all_dvs)==0:
    print("somthing wrong.")
    exit(0)

for f in tqdm(fns):
    fn = os.path.basename(f)
    dvs = fn.split('.')[0]
    if dvs not in all_dvs:
        os.remove(f)

